import type { ShoppingSection } from "./types";

export const SECTIONS: ShoppingSection[] = [
  "Fruta y verdura",
  "Panaderia",
  "Carniceria",
  "Pescaderia",
  "Charcuteria",
  "Lacteos y huevos",
  "Congelados",
  "Despensa",
  "Pasta, arroz y legumbres",
  "Conservas",
  "Desayuno y dulces",
  "Bebidas",
  "Limpieza",
  "Hogar y papel",
  "Higiene y farmacia",
  "Bebe y mascotas",
  "Otros",
];

export const DEFAULT_SECTION: ShoppingSection = "Otros";

export const SECTION_TERMS: Record<ShoppingSection, string[]> = {
  "Fruta y verdura": [
    "ajo",
    "aguacate",
    "apio",
    "berenjena",
    "brocoli",
    "calabacin",
    "cebolla",
    "cereza",
    "champiñon",
    "coliflor",
    "esparrago",
    "fresa",
    "kiwi",
    "lechuga",
    "limon",
    "mandarina",
    "manzana",
    "melon",
    "naranja",
    "patata",
    "pepino",
    "pera",
    "pimiento",
    "platano",
    "puerro",
    "sandia",
    "tomate",
    "uva",
    "zanahoria",
  ],
  Panaderia: ["barra", "bolleria", "croissant", "molde", "pan", "panecillo", "picos", "tortilla trigo"],
  Carniceria: ["albondiga", "bacon", "carne", "cerdo", "chuleta", "filete", "hamburguesa", "lomo", "pollo", "ternera"],
  Pescaderia: ["atun fresco", "bacalao", "calamar", "gamba", "langostino", "lubina", "merluza", "pescado", "salmon", "sardina"],
  Charcuteria: ["chorizo", "fuet", "jamon", "lomo embuchado", "mortadela", "pavo", "salami", "salchichon"],
  "Lacteos y huevos": ["batido", "huevo", "kefir", "leche", "mantequilla", "nata", "queso", "yogur"],
  Congelados: ["croqueta", "empanadilla", "helado", "hielo", "pizza congelada", "verdura congelada"],
  Despensa: ["aceite", "azucar", "caldo", "cereal", "chocolate", "cafe", "colacao", "galleta", "harina", "miel", "sal"],
  "Pasta, arroz y legumbres": ["arroz", "fideo", "garbanzo", "lenteja", "macarron", "pasta", "spaghetti", "tallarines"],
  Conservas: ["aceituna", "anchoa", "atun", "berberecho", "conserva", "esparrago lata", "mejillon", "sardinilla"],
  "Desayuno y dulces": ["bollos", "cacao", "crema cacao", "donut", "magdalena", "mermelada", "tostada"],
  Bebidas: ["agua", "cerveza", "coca cola", "fanta", "refresco", "vino", "zumo"],
  Limpieza: ["amoniaco", "detergente", "fregasuelos", "gel lavavajillas", "lejia", "limpiacristales", "suavizante"],
  "Hogar y papel": ["albal", "bolsa basura", "film", "papel cocina", "papel higienico", "servilleta"],
  "Higiene y farmacia": ["champu", "colonia", "desodorante", "gel", "ibuprofeno", "jabon", "pasta dientes", "toallita"],
  "Bebe y mascotas": ["arena gato", "comida gato", "comida perro", "pañal", "potito", "toallitas bebe"],
  Otros: [],
};
